#!/bin/bash
set -xeuo pipefail
# This script copies the manifests from the current directory
# into their installed location.
manifestdir=${1:-/usr/share/doc/bootc-base-imagectl/manifests}
mkdir -p "$manifestdir/"
for image in minimal standard minimal-plus iot; do
    # Embed the generic defaults
    cp -a $image $manifestdir/
    # And the Fedora-specific tweaks
    cp -a fedora-$image.yaml $manifestdir/
done
# Set the default
ln -s fedora-standard.yaml $manifestdir/default.yaml
# And install dependency manifests
cp -a fedora-includes $manifestdir
